spring:
  datasource:
    url: jdbc:mysql://localhost:3306/churchpressdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true


  flyway:
    baselineOnMigrate : true